# Generated by Django 5.1.5 on 2025-11-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20251107_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
