# Generated by Django 5.1.5 on 2025-11-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_payment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('clinic_scheduled', 'Clinic Scheduled'), ('patient_request', 'Patient Request'), ('referral', 'Referral')], default='patient_request', max_length=20),
        ),
    ]
