# Generated by Django 5.1.5 on 2025-11-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentreferral',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='appointment.appointment'),
        ),
    ]
