# Generated by Django 5.1.5 on 2025-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointmentreferral_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('clinic_scheduled', 'Clinic Scheduled'), ('patient_request', 'Patient Request'), ('referral', 'Referral')], default='clinic_scheduled', max_length=20),
        ),
    ]
