# Generated by Django 5.1.5 on 2025-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_patient_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
