# Generated by Django 5.1.5 on 2025-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_labresult_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
