# Generated by Django 5.1.5 on 2025-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_healthtips'),
        ('user', '0015_alter_useraccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtips',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthtips',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthtips',
            name='original_tip_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthtips',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed by Doctor'), ('modified', 'Modified by Doctor'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='healthtips',
            index=models.Index(fields=['status'], name='patient_hea_status_ab7ca1_idx'),
        ),
    ]
