# Generated by Django 5.1.5 on 2025-11-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_healthtips_confirmed_at_healthtips_is_auto_generated_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='healthtips',
            name='patient_hea_status_ab7ca1_idx',
        ),
        migrations.RemoveField(
            model_name='healthtips',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='healthtips',
            name='original_tip_text',
        ),
        migrations.RemoveField(
            model_name='healthtips',
            name='status',
        ),
    ]
